name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.
        
        **Before submitting:**
        - Check if the issue has already been reported
        - Check the [documentation](https://github.com/NGXSMK/ngxsmk-datepicker#readme) and [FAQ](https://github.com/NGXSMK/ngxsmk-datepicker/issues)
        - Try to reproduce the issue with the latest version

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear description of what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: If applicable, add a minimal code example to help reproduce the issue
      placeholder: |
        ```typescript
        // Your code here
        ```
      render: typescript

  - type: dropdown
    id: angular-version
    attributes:
      label: Angular Version
      description: Which version of Angular are you using?
      options:
        - "17.x"
        - "18.x"
        - "19.x"
        - "20.x"
        - "21.x"
        - "22.x"
        - "Other"
    validations:
      required: true

  - type: input
    id: datepicker-version
    attributes:
      label: ngxsmk-datepicker Version
      description: Which version of ngxsmk-datepicker are you using?
      placeholder: e.g., 1.9.1
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you seeing the issue on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: false

  - type: textarea
    id: console
    attributes:
      label: Console Errors
      description: Any errors in the browser console?
      placeholder: Paste console errors here (if any)
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I can provide a minimal reproduction case
          required: true

